#twompro toy
"""AWAKEN KOOII: gold jomaSB cardK			 fn8 (Boss Hunt)
GUARDIAN IMP: gold joma jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
OOHEHE: gold jomaSB weapB			 fn8 (Boss Hunt)
GUARDIAN IMP: jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold armB jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardK cardA			 fn8 (Boss Hunt)
AWAKEN KOOII: gold joma			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
GUARDIAN IMP: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold treasure			 fn8 (Boss Hunt)
GUARDIAN IMP: gold joma			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardA			 fn8 (Boss Hunt)
GUARDIAN IMP: joma			 fn8 (Boss Hunt)
DEVILANG: gold jomaSB experimentToken			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
GUARDIAN IMP: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardK			 fn8 (Boss Hunt)
GUARDIAN IMP: jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardK			 fn8 (Boss Hunt)
GUARDIAN IMP: jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardK			 fn8 (Boss Hunt)
GUARDIAN IMP: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold jomaSB			 fn8 (Boss Hunt)
GUARDIAN IMP: gold joma			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
OOHEEHEEK: gold			 fn8 (Boss Hunt)
DEVILANG: gold jomaSB			 fn8 (Boss Hunt)
Barslaf: hopefulMagicEssence ancient powder oldscroll			 fn8 (Boss Hunt)
Sephia: enchanted leather enchanted bone			 fn8 (Boss Hunt)
DEVILANG: oldScroll jomaSB experimentToken			 fn8 (Boss Hunt)
DEVILANG: gold oldscroll armA jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold treasure			 fn8 (Boss Hunt)
AWAKEN KOOII: treasure			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardK			 fn8 (Boss Hunt)
GUARDIAN IMP: gold joma			 fn8 (Boss Hunt)
AWAKEN KOOII: cardK weapB			 fn8 (Boss Hunt)
GUARDIAN IMP: gold			 fn8 (Boss Hunt)
GUARDIAN IMP: gold treasure			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardK			 fn8 (Boss Hunt)
GUARDIAN IMP: gold jomaSB			 fn8 (Boss Hunt)
GUARDIAN IMP: gold			 fn8 (Boss Hunt)
GUARDIAN IMP: gold joma jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold armB joma			 fn8 (Boss Hunt)
GUARDIAN IMP: jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: armB			 fn8 (Boss Hunt)
GUARDIAN IMP: lost			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
GUARDIAN IMP: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
GUARDIAN IMP: gold joma			 fn8 (Boss Hunt)
AWAKEN KOOII: gold joma			 fn8 (Boss Hunt)
AWAKEN KOOII: gold joma			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardA			 fn8 (Boss Hunt)
AWAKEN KOOII: gold joma			 fn8 (Boss Hunt)
AWAKEN KOOII: gold armB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardA			 fn8 (Boss Hunt)
AWAKEN KOOII: joma			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold joma			 fn8 (Boss Hunt)
DEVILANG: gold token oldScroll  jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardA cardK jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold joma armB			 fn8 (Boss Hunt)
DEVILANG: gold oldScroll jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
Barslaf: armS oldScroll star piece crownrockbottle hopefulmagicessence			 fn8 (Boss Hunt)
Actaemon: gold pink oldscroll			 fn8 (Boss Hunt)
DEVILANG: gold treasure jomaSB			 fn8 (Boss Hunt)
DEVILANG: oldScroll jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold armB			 fn8 (Boss Hunt)
DEVILANG: gold os jomaSB adventurerbag			 fn8 (Boss Hunt)
AWAKEN KOOII: air			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold treasure			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardA			 fn8 (Boss Hunt)
AWAKEN KOOII: gold joma sleepyKooii			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold jomaSB weapB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardK			 fn8 (Boss Hunt)
AWAKEN KOOII: gold weapB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: armB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: sharplongsowrd			 fn8 (Boss Hunt)
DEVILANG: gold jomaSB token			 fn8 (Boss Hunt)
AWAKEN KOOII: gold treasure cardA cardK			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold weapB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
DEVILANG: gold os jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold armB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold treasure			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
DEVILANG: gold jomaSB potionbag			 fn8 (Boss Hunt)
AWAKEN KOOII: gold joma			 fn8 (Boss Hunt)
AWAKEN KOOII: air			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
DEVILANG: gold os jomaSB			 fn8 (Boss Hunt)
AWAKEN KOOII: gold cardK			 fn8 (Boss Hunt)
AWAKEN KOOII: armB weapB cardA			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
AWAKEN KOOII: gold			 fn8 (Boss Hunt)
DEVILANG: gold jomaSB			 fn8 (Boss Hunt)
DEVILANG: gold os jomaSB			 fn8 (Boss Hunt)
DEVILANG: gold armA jomaSB			 fn8 (Boss Hunt)
DEVILANG: gold os jomaSB			 fn8 (Boss Hunt)"""


